### ISSUE TITLE
Auto pull in references icons in manifest config

### ISSUE THREAD

**Issue by kalvenschraut** [vite-pwa/vite-plugin-pwa#211]
I was wondering if it would be possible to have any icons that are referenced to the relative file path in the vite project would then be picked up as a static asset like referencing a static asset in source code. Then the generated manifest would point to the generated icon i.e. 

set the below config

```js
VitePWA({
  manifest: {
    icons: [{
      src: './src/assets/images/android-chrome-192x192.png'
      sizes: '192x182',
      type: 'image/png'
    }]
  }
})
```

The plugin then will generate the manifest referencing the filepath generated by vite similar to how vite does static asset handling. With my setup of assetsDir: 'static' that  means I would expect the generated filepath to be something like `/static/android-chrome-192x192.cded8a63.png. 

Currently I have to have any of the above icons in my public directory.

**Comment by userquin** [comment]
@kalvenschraut workbox is file based, we need to do some additional work: the `manifest.webmanifest` should be changed (replace each icon src with the final asset name traversing  the vite bundle map and find a match) but also the sw precache manifest, since we also need to add/check those entries: for example, if we include an icon from assets, this asset will be excluded by workbox since the default glob pattern doesn't include images files (https://vite-plugin-pwa.netlify.app/guide/static-assets.html#static-assets-handling), but it you change the `globPatterns` to include images, workbox will include them. 

Once #573 merged I'll check if we can add this feature.

**Comment by alkanna** [comment]
Hey @userquin , any news on this ?
