### ISSUE TITLE
vite sourcemap: 'hidden' doesn't quite work

### ISSUE THREAD

**Issue by 719media** [vite-pwa/vite-plugin-pwa#566]
If vite config is `build.sourcemap: 'hidden';`, the sourcemap is correctly generated for `service-worker.js.map` and `workbox.js.map`, but the sourceMappingURL is erroneously still included in the minified js files `service-worker.js` and `workbox.js`, even tho it should be hidden from inclusion at the end of the files.

It looks like vite-plugin-pwa coerces the value of build.sourcemap to a boolean, which means it isn't able to properly use the value.

**Comment by 719media** [comment]
I see the real issue is workbox:
https://github.com/GoogleChrome/workbox/issues/2559

Once (if ever) this is fixed, it will then need to be updated in this repo...

**Comment by userquin** [comment]
@719media I guess the problem in Vite build and/or workbox-build: by default the pwa plugin will build the sw using `es` format, esbuild will be used (https://github.com/vite-pwa/vite-plugin-pwa/pull/629 includes the sourcefile), but I'm not sure what happens when calling `workbox injectManifest`...

FYI: We're checking this another repo, this repo will use it soon, it seems very active (it is a workbox fork):
https://github.com/serwist/serwist

**Comment by userquin** [comment]
@719media should be fixed in #629 , you will be able to add this 4 new options to `injectManifest`:
- minify
- sourcemap
- enableWrokboxModulesLogs
- target
